blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/yevgeniusr/ts-monorepo-boilerplate/discussions
    about: Ask questions and discuss ideas with the community
  - name: Security Issue
    url: https://github.com/yevgeniusr/ts-monorepo-boilerplate/security/advisories/new
    about: Report a security vulnerability (please do not open a public issue)
